version: "3.9"

volumes:
  vol-mongodb:
    driver: local

services:
  mongodb:
    image: "mongo:latest"
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=YOUR_PASSWORD
    volumes:
      - vol-mongodb:/data/db
