version: "3.9"

volumes:
  data:
    driver: local

services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=YOUR_PASSWORD
    volumes:
      - data:/data/db
      - ./dump:/home/dump
